// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQHqpcolsr4jd3u52NrA2HskvOpujIGow',
    appId: '1:88225518587:web:92228fd5f8066d6471b15e',
    messagingSenderId: '88225518587',
    projectId: 'fluter-test-d3517',
    authDomain: 'fluter-test-d3517.firebaseapp.com',
    storageBucket: 'fluter-test-d3517.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgbqcPY6sEfwi69dsAbKHgjUgrFwo2GWE',
    appId: '1:88225518587:android:821ce637c0d36be771b15e',
    messagingSenderId: '88225518587',
    projectId: 'fluter-test-d3517',
    storageBucket: 'fluter-test-d3517.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnGIOLFasAXLeih4k4C9VGq78rv4FlfD4',
    appId: '1:88225518587:ios:2436753a275d762f71b15e',
    messagingSenderId: '88225518587',
    projectId: 'fluter-test-d3517',
    storageBucket: 'fluter-test-d3517.firebasestorage.app',
    iosBundleId: 'com.example.crudfluter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnGIOLFasAXLeih4k4C9VGq78rv4FlfD4',
    appId: '1:88225518587:ios:2436753a275d762f71b15e',
    messagingSenderId: '88225518587',
    projectId: 'fluter-test-d3517',
    storageBucket: 'fluter-test-d3517.firebasestorage.app',
    iosBundleId: 'com.example.crudfluter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQHqpcolsr4jd3u52NrA2HskvOpujIGow',
    appId: '1:88225518587:web:97112246978e86bb71b15e',
    messagingSenderId: '88225518587',
    projectId: 'fluter-test-d3517',
    authDomain: 'fluter-test-d3517.firebaseapp.com',
    storageBucket: 'fluter-test-d3517.firebasestorage.app',
  );
}
